id: 9266fdb67bb34ecc939ccd55142f3306
initial_creation_type: ebook
created_at: 14/04/2021
last_modified_at: 25/11/2021
source_metadata:
  title: test
  subtitle: ''
  authors:
  - test
  collection: ''
  publisher: ''
  id: test
  cover: tmpu5xka87f.jpg
  credit: tmpi8_9rs_a.jpg
